name: Report Bug
description: Report something that's broken or not working right.
title: "[BUG] "
labels: ["bug"]
body:
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Describe the issue in detail.
      placeholder: "It crashed when I clicked X..."
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Steps to Reproduce
      description: How can we replicate the bug?
      placeholder: "Step-by-step instructions to trigger the issue"
    validations:
      required: true

  - type: dropdown
    id: version
    attributes:
      label: App Version
      description: Which version were you using when the bug occurred?
      options:
        - "1.0.1-3"
        - "1.0.1-2"
        - "1.0.1-1"
        - "1.0.1"
        - "1.0.0"
        - "Below 1.0.0"
    validations:
      required: true

  - type: dropdown
    id: store-edition
    attributes:
      label: Store Edition
      description: Where did you get this version of the app?
      options:
        - "GitHub Edition"
        - "Steam Edition"
    validations:
      required: true
